version: "3.7"

services:
  client-serve:
    image: node:${NODE_VER}
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./config:/app/config:ro
      - ./public:/app/public:ro
      - ./src:/app/src:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - ./package.json:/app/package.json:ro
      - ./local-entry.sh:/app/local-entry.sh:ro
    entrypoint: ["sh", "-e", "./local-entry.sh"]
    ports:
      - 8080:3000
